/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminModuleRouteImport } from './routes/admin.$module'
import { Route as ApiSaudeRouteImport } from './routes/api.saude'
import { Route as AuthConfirmarRouteImport } from './routes/auth.confirmar'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as ClienteFidelidadeRouteImport } from './routes/cliente.fidelidade'
import { Route as ClientePerfilRouteImport } from './routes/cliente.perfil'
import { Route as ApiEmailsProcessarRouteImport } from './routes/api.emails.processar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModuleRoute = AdminModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSaudeRoute = ApiSaudeRouteImport.update({
  id: '/api/saude',
  path: '/api/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmarRoute = AuthConfirmarRouteImport.update({
  id: '/auth/confirmar',
  path: '/auth/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteFidelidadeRoute = ClienteFidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const ApiEmailsProcessarRoute = ApiEmailsProcessarRouteImport.update({
  id: '/api/emails/processar',
  path: '/api/emails/processar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento': typeof AgendamentoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$module': typeof AdminModuleRoute
  '/api/saude': typeof ApiSaudeRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/cliente/fidelidade': typeof ClienteFidelidadeRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/api/emails/processar': typeof ApiEmailsProcessarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$module': typeof AdminModuleRoute
  '/api/saude': typeof ApiSaudeRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/cliente/fidelidade': typeof ClienteFidelidadeRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/api/emails/processar': typeof ApiEmailsProcessarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento': typeof AgendamentoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$module': typeof AdminModuleRoute
  '/api/saude': typeof ApiSaudeRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/cliente/fidelidade': typeof ClienteFidelidadeRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/api/emails/processar': typeof ApiEmailsProcessarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendamento'
    | '/cliente'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/robots.txt'
    | '/servicos'
    | '/sitemap.xml'
    | '/admin/$module'
    | '/api/saude'
    | '/auth/confirmar'
    | '/cliente/fidelidade'
    | '/cliente/perfil'
    | '/admin/'
    | '/cliente/'
    | '/api/emails/processar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/robots.txt'
    | '/servicos'
    | '/sitemap.xml'
    | '/admin/$module'
    | '/api/saude'
    | '/auth/confirmar'
    | '/cliente/fidelidade'
    | '/cliente/perfil'
    | '/admin'
    | '/cliente'
    | '/api/emails/processar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendamento'
    | '/cliente'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/robots.txt'
    | '/servicos'
    | '/sitemap.xml'
    | '/admin/$module'
    | '/api/saude'
    | '/auth/confirmar'
    | '/cliente/fidelidade'
    | '/cliente/perfil'
    | '/admin/'
    | '/cliente/'
    | '/api/emails/processar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendamentoRoute: typeof AgendamentoRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  ProdutosRoute: typeof ProdutosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSaudeRoute: typeof ApiSaudeRoute
  AuthConfirmarRoute: typeof AuthConfirmarRoute
  ApiEmailsProcessarRoute: typeof ApiEmailsProcessarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$module': {
      id: '/admin/$module'
      path: '/$module'
      fullPath: '/admin/$module'
      preLoaderRoute: typeof AdminModuleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/saude': {
      id: '/api/saude'
      path: '/api/saude'
      fullPath: '/api/saude'
      preLoaderRoute: typeof ApiSaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirmar': {
      id: '/auth/confirmar'
      path: '/auth/confirmar'
      fullPath: '/auth/confirmar'
      preLoaderRoute: typeof AuthConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/fidelidade': {
      id: '/cliente/fidelidade'
      path: '/fidelidade'
      fullPath: '/cliente/fidelidade'
      preLoaderRoute: typeof ClienteFidelidadeRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/api/emails/processar': {
      id: '/api/emails/processar'
      path: '/api/emails/processar'
      fullPath: '/api/emails/processar'
      preLoaderRoute: typeof ApiEmailsProcessarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminModuleRoute: typeof AdminModuleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModuleRoute: AdminModuleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteRouteChildren {
  ClienteFidelidadeRoute: typeof ClienteFidelidadeRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteFidelidadeRoute: ClienteFidelidadeRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendamentoRoute: AgendamentoRoute,
  ClienteRoute: ClienteRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  ProdutosRoute: ProdutosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSaudeRoute: ApiSaudeRoute,
  AuthConfirmarRoute: AuthConfirmarRoute,
  ApiEmailsProcessarRoute: ApiEmailsProcessarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
